In [35]:
import pandas as pd

DATA = pd.read_csv('outputs\\AMIcsv\\EN2001a.count.csv', delimiter=',') # , names=['start', 'end', 'duration', 'count']

In [39]:
args = {'useVAD': True, 'path': 'F:\\' }


def func(useVAD, path):
    print(useVAD, path)

func(**args)

True F:\

In [40]:
args_1 = {
    'useVAD': True,
    'path': 'F:\\'
}

func(**args_1)

True F:\

In [11]:
from utils_2 import ananas

print(ananas)

[4, 5, 6]

In [9]:
import os
import pandas as pd

files = os.listdir('data\\AMI\\Count')
    
#DATA = pd.read_csv('data\\AMI\\Count\\' + files[0], delimiter=',')

DATA = pd.DataFrame({'start': [], 'duration': [], 'count': []})

In [12]:
DATA

        start  duration  count
0        0.00      3.34    0.0
1        3.34      0.54    1.0
2        3.88      1.69    0.0
3        5.57      0.03    1.0
4        5.60      0.34    2.0
...       ...       ...    ...
1411  2307.65      0.39    0.0
1412  2308.04      0.21    1.0
1413  2308.25     15.65    0.0
1414  2323.90      0.49    1.0
1415  2324.39     17.21    0.0

[164811 rows x 3 columns]

In [11]:


for f in files:
    file_csv = 'data\\AMI\\Count\\' + f # путь к файлам

    data = pd.read_csv(file_csv, delimiter=',') # колонки - start, duration, count или (start, end, duration, count)
    
    #DATA.join(data)
    DATA = pd.concat([DATA, data])

In [54]:
DATA[(DATA.count == 1) & (DATA.duration > 0.1)]

Empty DataFrame
Columns: [start, duration, count]
Index: []

In [13]:
duration = [[], [], [], [], []]

data = DATA.values

for st, dur, cnt in data:
    duration[int(cnt)].append(dur)

In [14]:
import numpy as numpy

for i in range(len(duration)):
    print('Класс:', i)
    print('Общая длительность', np.sum(duration[i]))
    print('Средняя длительность', np.mean(duration[i]))
    print('Минимальная длительность', np.min(duration[i]))
    print('Максимальная длительность', np.max(duration[i]))
    print('Медианная длительность', np.median(duration[i]))
    
    print('\n')

Класс: 0
Общая длительность 66028.193875
Средняя длительность 1.9296897412105094
Минимальная длительность 0.0099999999997635
Максимальная длительность 815.428625
Медианная длительность 1.0199999999999818


Класс: 1
Общая длительность 250841.88900000005
Средняя длительность 3.3389935307820306
Минимальная длительность 0.0099999999993087
Максимальная длительность 84.6400000000001
Медианная длительность 1.7000000000000457


Класс: 2
Общая длительность 35340.98599999996
Средняя длительность 0.7393047716670493
Минимальная длительность 0.0099999999997635
Максимальная длительность 11.849999999999907
Медианная длительность 0.4600000000000364


Класс: 3
Общая длительность 3790.013999999993
Средняя длительность 0.5237719734660023
Минимальная длительность 0.0099999999997635
Максимальная длительность 14.340000000000032
Медианная длительность 0.3399999999996907


Класс: 4
Общая длительность 196.73000000000212
Средняя длительность 0.4575116279069817
Минимальная длительность 0.0099999999997635
Максимальная длительность 5.1200000000000045
Медианная длительность 0.2899999999999636

In [74]:
duration_1 = [[], [], [], [], []]

data = DATA.values

for st, dur, cnt in data:
    duration_1[int(cnt)].append([st, dur, int(cnt)])

In [78]:
duration_1[4]

In [94]:
dur_4 = pd.DataFrame(duration_1[4])

dur_4 = dur_4.sort_values(by=1, ascending=False)

In [95]:
dur_4 = dur_4.values
print(dur_4)

for d in dur_4:
    print(d)

[[6.96900e+02 5.12000e+00 4.00000e+00]
 [9.00440e+02 4.09000e+00 4.00000e+00]
 [2.50120e+02 3.21000e+00 4.00000e+00]
 ...
 [1.57299e+03 1.00000e-02 4.00000e+00]
 [1.41247e+03 1.00000e-02 4.00000e+00]
 [2.18261e+03 1.00000e-02 4.00000e+00]]
[696.9    5.12   4.  ]
[900.44   4.09   4.  ]
[250.12   3.21   4.  ]
[1362.75    3.18    4.  ]
[1113.53    2.87    4.  ]
[191.15   2.76   4.  ]
[2.78682e+03 2.62000e+00 4.00000e+00]
[1855.9     2.59    4.  ]
[1364.86    2.51    4.  ]
[335.9    2.31   4.  ]
[2.96965e+03 2.27000e+00 4.00000e+00]
[1372.83    2.07    4.  ]
[731.07   1.97   4.  ]
[945.97   1.74   4.  ]
[142.83   1.74   4.  ]
[236.88   1.67   4.  ]
[1251.15    1.62    4.  ]
[1105.65    1.6     4.  ]
[1.74511e+03 1.58000e+00 4.00000e+00]
[391.6    1.43   4.  ]
[1.48125e+03 1.41000e+00 4.00000e+00]
[1.56154e+03 1.40000e+00 4.00000e+00]
[928.23   1.4    4.  ]
[1.40473e+03 1.38000e+00 4.00000e+00]
[1.54186e+03 1.34000e+00 4.00000e+00]
[947.95   1.3    4.  ]
[2.20533e+03 1.28000e+00 4.00000e+00]
[1198.49    1.27    4.  ]
[3.10632e+03 1.27000e+00 4.00000e+00]
[1.7628e+03 1.2700e+00 4.0000e+00]
[931.03   1.26   4.  ]
[1178.93    1.23    4.  ]
[882.79   1.19   4.  ]
[1.74246e+03 1.17000e+00 4.00000e+00]
[1.35943e+03 1.14000e+00 4.00000e+00]
[900.15   1.12   4.  ]
[798.     1.11   4.  ]
[945.91   1.09   4.  ]
[668.12   1.07   4.  ]
[789.83   1.06   4.  ]
[534.22   1.04   4.  ]
[1.73642e+03 1.02000e+00 4.00000e+00]
[923.76   1.01   4.  ]
[1.07247e+03 1.01000e+00 4.00000e+00]
[1.41027e+03 9.70000e-01 4.00000e+00]
[677.98   0.96   4.  ]
[1.71259e+03 9.50000e-01 4.00000e+00]
[2.13615e+03 9.40000e-01 4.00000e+00]
[2.54058e+03 9.30000e-01 4.00000e+00]
[677.35   0.93   4.  ]
[3.39628e+03 9.30000e-01 4.00000e+00]
[360.31   0.91   4.  ]
[2.08999e+03 9.00000e-01 4.00000e+00]
[2.43826e+03 9.00000e-01 4.00000e+00]
[1.16681e+03 8.90000e-01 4.00000e+00]
[501.78   0.89   4.  ]
[1.57891e+03 8.80000e-01 4.00000e+00]
[3.32889e+03 8.70000e-01 4.00000e+00]
[1.12078e+03 8.60000e-01 4.00000e+00]
[2.3901e+03 8.6000e-01 4.0000e+00]
[9.6488e+02 8.6000e-01 4.0000e+00]
[691.11   0.85   4.  ]
[3.23987e+03 8.50000e-01 4.00000e+00]
[1.47374e+03 8.50000e-01 4.00000e+00]
[1.36859e+03 8.20000e-01 4.00000e+00]
[1.56811e+03 8.20000e-01 4.00000e+00]
[1.02808e+03 8.20000e-01 4.00000e+00]
[1.08426e+03 8.20000e-01 4.00000e+00]
[9.038e+02 8.000e-01 4.000e+00]
[1.05965e+03 7.80000e-01 4.00000e+00]
[8.1108e+02 7.5000e-01 4.0000e+00]
[1.62158e+03 7.50000e-01 4.00000e+00]
[273.66   0.73   4.  ]
[1.95774e+03 7.10000e-01 4.00000e+00]
[346.9    0.71   4.  ]
[1.15073e+03 7.10000e-01 4.00000e+00]
[7.0641e+02 7.0000e-01 4.0000e+00]
[1.4169e+03 7.0000e-01 4.0000e+00]
[601.     0.69   4.  ]
[1.19256e+03 6.80000e-01 4.00000e+00]
[7.6782e+02 6.8000e-01 4.0000e+00]
[270.7    0.67   4.  ]
[9.4259e+02 6.7000e-01 4.0000e+00]
[569.74   0.67   4.  ]
[1.39066e+03 6.70000e-01 4.00000e+00]
[3.5209e+03 6.6000e-01 4.0000e+00]
[9.0621e+02 6.5000e-01 4.0000e+00]
[7.1821e+02 6.4000e-01 4.0000e+00]
[2.07288e+03 6.40000e-01 4.00000e+00]
[397.15   0.63   4.  ]
[1.7731e+03 6.2000e-01 4.0000e+00]
[259.36   0.62   4.  ]
[7.7832e+02 6.2000e-01 4.0000e+00]
[1.25705e+03 6.10000e-01 4.00000e+00]
[1.59052e+03 6.10000e-01 4.00000e+00]
[6.5549e+02 6.1000e-01 4.0000e+00]
[29.93  0.61  4.  ]
[1.76889e+03 6.10000e-01 4.00000e+00]
[1.78586e+03 6.00000e-01 4.00000e+00]
[1.87538e+03 6.00000e-01 4.00000e+00]
[9.534e+02 5.900e-01 4.000e+00]
[6.9154e+02 5.9000e-01 4.0000e+00]
[1.72719e+03 5.80000e-01 4.00000e+00]
[1.17841e+03 5.80000e-01 4.00000e+00]
[8.9813e+02 5.7000e-01 4.0000e+00]
[116.39   0.57   4.  ]
[1.15671e+03 5.70000e-01 4.00000e+00]
[6.7224e+02 5.6000e-01 4.0000e+00]
[2.52436e+03 5.60000e-01 4.00000e+00]
[2.20935e+03 5.60000e-01 4.00000e+00]
[1.32781e+03 5.50000e-01 4.00000e+00]
[298.04   0.55   4.  ]
[2.02677e+03 5.40000e-01 4.00000e+00]
[1.209084e+03 5.400000e-01 4.000000e+00]
[1.85437e+03 5.30000e-01 4.00000e+00]
[1.67033e+03 5.30000e-01 4.00000e+00]
[1.98056e+03 5.30000e-01 4.00000e+00]
[1.44189e+03 5.20000e-01 4.00000e+00]
[9.0014e+02 5.1000e-01 4.0000e+00]
[1.32272e+03 5.10000e-01 4.00000e+00]
[1.06964e+03 5.10000e-01 4.00000e+00]
[8.3876e+02 5.0000e-01 4.0000e+00]
[2.00693e+03 5.00000e-01 4.00000e+00]
[1.78839e+03 5.00000e-01 4.00000e+00]
[1.12752e+03 4.90000e-01 4.00000e+00]
[6.2393e+02 4.9000e-01 4.0000e+00]
[2.37243e+03 4.80000e-01 4.00000e+00]
[1.27601e+03 4.80000e-01 4.00000e+00]
[9.9078e+02 4.8000e-01 4.0000e+00]
[1.12945e+03 4.80000e-01 4.00000e+00]
[5.5645e+02 4.8000e-01 4.0000e+00]
[2.26295e+03 4.70000e-01 4.00000e+00]
[6.9368e+02 4.7000e-01 4.0000e+00]
[1.04941e+03 4.70000e-01 4.00000e+00]
[1.26098e+03 4.70000e-01 4.00000e+00]
[1.79233e+03 4.70000e-01 4.00000e+00]
[1.50088e+03 4.70000e-01 4.00000e+00]
[289.2    0.46   4.  ]
[6.8074e+02 4.6000e-01 4.0000e+00]
[3.03943e+03 4.50000e-01 4.00000e+00]
[1.39536e+03 4.50000e-01 4.00000e+00]
[8.1491e+02 4.4000e-01 4.0000e+00]
[1.49152e+03 4.40000e-01 4.00000e+00]
[5.9301e+02 4.4000e-01 4.0000e+00]
[5.6249e+02 4.4000e-01 4.0000e+00]
[8.9572e+02 4.4000e-01 4.0000e+00]
[1.58697e+03 4.30000e-01 4.00000e+00]
[4.7279e+02 4.3000e-01 4.0000e+00]
[1.67907e+03 4.20000e-01 4.00000e+00]
[118.63   0.42   4.  ]
[1.46029e+03 4.10000e-01 4.00000e+00]
[5.7557e+02 4.1000e-01 4.0000e+00]
[1.02334e+03 4.10000e-01 4.00000e+00]
[1.92935e+03 4.00000e-01 4.00000e+00]
[1.14354e+03 4.00000e-01 4.00000e+00]
[9.1741e+02 4.0000e-01 4.0000e+00]
[6.9149e+02 4.0000e-01 4.0000e+00]
[1.8897e+03 4.0000e-01 4.0000e+00]
[1.69131e+03 3.90000e-01 4.00000e+00]
[1.40362e+03 3.90000e-01 4.00000e+00]
[6.0458e+02 3.9000e-01 4.0000e+00]
[4.0404e+02 3.9000e-01 4.0000e+00]
[1.46817e+03 3.90000e-01 4.00000e+00]
[2.26719e+03 3.90000e-01 4.00000e+00]
[1.01494e+03 3.80000e-01 4.00000e+00]
[7.0784e+02 3.8000e-01 4.0000e+00]
[1.23922e+03 3.80000e-01 4.00000e+00]
[2.21872e+03 3.70000e-01 4.00000e+00]
[9.1797e+02 3.7000e-01 4.0000e+00]
[1.57033e+03 3.60000e-01 4.00000e+00]
[3.40954e+03 3.60000e-01 4.00000e+00]
[9.3842e+02 3.6000e-01 4.0000e+00]
[1.4202e+03 3.6000e-01 4.0000e+00]
[1.97415e+03 3.60000e-01 4.00000e+00]
[1.3783e+03 3.5000e-01 4.0000e+00]
[7.7853e+02 3.5000e-01 4.0000e+00]
[9.5725e+02 3.5000e-01 4.0000e+00]
[219.94   0.35   4.  ]
[8.7332e+02 3.5000e-01 4.0000e+00]
[1.45504e+03 3.40000e-01 4.00000e+00]
[9.7554e+02 3.4000e-01 4.0000e+00]
[91.19  0.34  4.  ]
[1.17526e+03 3.40000e-01 4.00000e+00]
[1.29871e+03 3.40000e-01 4.00000e+00]
[1.05507e+03 3.30000e-01 4.00000e+00]
[5.9337e+02 3.3000e-01 4.0000e+00]
[1.1404e+03 3.3000e-01 4.0000e+00]
[1.02543e+03 3.30000e-01 4.00000e+00]
[1.92404e+03 3.30000e-01 4.00000e+00]
[2.37811e+03 3.30000e-01 4.00000e+00]
[3.36145e+03 3.20000e-01 4.00000e+00]
[2.5481e+03 3.2000e-01 4.0000e+00]
[5.8665e+02 3.2000e-01 4.0000e+00]
[1.74576e+03 3.20000e-01 4.00000e+00]
[1.7478e+03 3.2000e-01 4.0000e+00]
[1.3816e+03 3.1000e-01 4.0000e+00]
[5.5314e+02 3.1000e-01 4.0000e+00]
[283.03   0.31   4.  ]
[125.03   0.31   4.  ]
[1.68623e+03 3.10000e-01 4.00000e+00]
[9.7285e+02 3.1000e-01 4.0000e+00]
[2.17987e+03 3.10000e-01 4.00000e+00]
[1.09598e+03 3.10000e-01 4.00000e+00]
[1.13011e+03 3.00000e-01 4.00000e+00]
[2.27324e+03 3.00000e-01 4.00000e+00]
[7.6942e+02 3.0000e-01 4.0000e+00]
[285.42   0.3    4.  ]
[1.83781e+03 3.00000e-01 4.00000e+00]
[8.2385e+02 3.0000e-01 4.0000e+00]
[1.15027e+03 3.00000e-01 4.00000e+00]
[1.29404e+03 3.00000e-01 4.00000e+00]
[6.027e+02 2.900e-01 4.000e+00]
[1.17675e+03 2.90000e-01 4.00000e+00]
[5.7319e+02 2.9000e-01 4.0000e+00]
[1.63867e+03 2.90000e-01 4.00000e+00]
[7.1836e+02 2.9000e-01 4.0000e+00]
[1.27207e+03 2.90000e-01 4.00000e+00]
[1.75561e+03 2.80000e-01 4.00000e+00]
[3.22956e+03 2.80000e-01 4.00000e+00]
[8.5093e+02 2.8000e-01 4.0000e+00]
[3.7634e+02 2.8000e-01 4.0000e+00]
[1.14653e+03 2.80000e-01 4.00000e+00]
[1.48714e+03 2.80000e-01 4.00000e+00]
[1.36528e+03 2.80000e-01 4.00000e+00]
[1.23932e+03 2.80000e-01 4.00000e+00]
[6.4699e+02 2.8000e-01 4.0000e+00]
[1.91729e+03 2.80000e-01 4.00000e+00]
[9.4482e+02 2.8000e-01 4.0000e+00]
[1.69896e+03 2.70000e-01 4.00000e+00]
[1.01546e+03 2.70000e-01 4.00000e+00]
[1.27872e+03 2.60000e-01 4.00000e+00]
[1.60689e+03 2.60000e-01 4.00000e+00]
[1.45106e+03 2.60000e-01 4.00000e+00]
[7.7089e+02 2.5000e-01 4.0000e+00]
[1.37614e+03 2.50000e-01 4.00000e+00]
[9.7828e+02 2.5000e-01 4.0000e+00]
[1.94239e+03 2.50000e-01 4.00000e+00]
[1.33786e+03 2.50000e-01 4.00000e+00]
[1.39857e+03 2.50000e-01 4.00000e+00]
[2.16052e+03 2.50000e-01 4.00000e+00]
[1.47405e+03 2.50000e-01 4.00000e+00]
[1.70811e+03 2.50000e-01 4.00000e+00]
[2.46835e+03 2.40000e-01 4.00000e+00]
[1.04103e+03 2.40000e-01 4.00000e+00]
[1.77098e+03 2.40000e-01 4.00000e+00]
[4.0426e+02 2.4000e-01 4.0000e+00]
[228.66   0.24   4.  ]
[41.2   0.24  4.  ]
[2.53142e+03 2.40000e-01 4.00000e+00]
[1.33981e+03 2.30000e-01 4.00000e+00]
[2.23777e+03 2.30000e-01 4.00000e+00]
[1.0158e+03 2.3000e-01 4.0000e+00]
[1.88176e+03 2.30000e-01 4.00000e+00]
[3.8543e+02 2.2000e-01 4.0000e+00]
[9.8983e+02 2.2000e-01 4.0000e+00]
[2.05567e+03 2.20000e-01 4.00000e+00]
[2.16427e+03 2.20000e-01 4.00000e+00]
[1.22309e+03 2.10000e-01 4.00000e+00]
[2.6676e+02 2.1000e-01 4.0000e+00]
[2.23152e+03 2.10000e-01 4.00000e+00]
[1.80144e+03 2.10000e-01 4.00000e+00]
[182.17   0.21   4.  ]
[5.3544e+02 2.1000e-01 4.0000e+00]
[5.9069e+02 2.1000e-01 4.0000e+00]
[1.38991e+03 2.10000e-01 4.00000e+00]
[3.29249e+03 2.00000e-01 4.00000e+00]
[1.93632e+03 2.00000e-01 4.00000e+00]
[5.7463e+02 2.0000e-01 4.0000e+00]
[1.97331e+03 2.00000e-01 4.00000e+00]
[4.3704e+02 2.0000e-01 4.0000e+00]
[7.3572e+02 2.0000e-01 4.0000e+00]
[5.6558e+02 2.0000e-01 4.0000e+00]
[1.18666e+03 2.00000e-01 4.00000e+00]
[9.0168e+02 1.9000e-01 4.0000e+00]
[1.43647e+03 1.90000e-01 4.00000e+00]
[3.36334e+03 1.90000e-01 4.00000e+00]
[1.69295e+03 1.90000e-01 4.00000e+00]
[8.7266e+02 1.9000e-01 4.0000e+00]
[2.03449e+03 1.90000e-01 4.00000e+00]
[2.11215e+03 1.90000e-01 4.00000e+00]
[1.70153e+03 1.90000e-01 4.00000e+00]
[2.4714e+03 1.9000e-01 4.0000e+00]
[1.78225e+03 1.90000e-01 4.00000e+00]
[1.0082e+03 1.9000e-01 4.0000e+00]
[3.40595e+03 1.80000e-01 4.00000e+00]
[9.7141e+02 1.8000e-01 4.0000e+00]
[1.50512e+03 1.80000e-01 4.00000e+00]
[3.3855e+02 1.8000e-01 4.0000e+00]
[65.86  0.18  4.  ]
[3.5767e+02 1.8000e-01 4.0000e+00]
[3.8444e+02 1.8000e-01 4.0000e+00]
[5.3062e+02 1.8000e-01 4.0000e+00]
[3.50198e+03 1.80000e-01 4.00000e+00]
[1.73434e+03 1.70000e-01 4.00000e+00]
[2.9778e+02 1.7000e-01 4.0000e+00]
[8.137e+02 1.700e-01 4.000e+00]
[5.5596e+02 1.7000e-01 4.0000e+00]
[1.14238e+03 1.70000e-01 4.00000e+00]
[1.75683e+03 1.60000e-01 4.00000e+00]
[1.14424e+03 1.60000e-01 4.00000e+00]
[9.8532e+02 1.6000e-01 4.0000e+00]
[8.3575e+02 1.6000e-01 4.0000e+00]
[1.18165e+03 1.60000e-01 4.00000e+00]
[1.30113e+03 1.60000e-01 4.00000e+00]
[1.22038e+03 1.60000e-01 4.00000e+00]
[9.1231e+02 1.5000e-01 4.0000e+00]
[1.02902e+03 1.50000e-01 4.00000e+00]
[2.00345e+03 1.50000e-01 4.00000e+00]
[1.79965e+03 1.50000e-01 4.00000e+00]
[5.28922e+03 1.50000e-01 4.00000e+00]
[2.36341e+03 1.40000e-01 4.00000e+00]
[3.33949e+03 1.40000e-01 4.00000e+00]
[18.95  0.14  4.  ]
[4.882e+02 1.400e-01 4.000e+00]
[8.5727e+02 1.4000e-01 4.0000e+00]
[8.9665e+02 1.4000e-01 4.0000e+00]
[7.7097e+02 1.4000e-01 4.0000e+00]
[1.88588e+03 1.40000e-01 4.00000e+00]
[2.04221e+03 1.40000e-01 4.00000e+00]
[1.79269e+03 1.40000e-01 4.00000e+00]
[2.30192e+03 1.40000e-01 4.00000e+00]
[2.11244e+03 1.40000e-01 4.00000e+00]
[2.12304e+03 1.30000e-01 4.00000e+00]
[5.7312e+02 1.3000e-01 4.0000e+00]
[9.112e+02 1.300e-01 4.000e+00]
[2.4785e+02 1.3000e-01 4.0000e+00]
[6.9716e+02 1.3000e-01 4.0000e+00]
[7.4051e+02 1.3000e-01 4.0000e+00]
[7.9325e+02 1.3000e-01 4.0000e+00]
[1.68645e+03 1.30000e-01 4.00000e+00]
[2.21541e+03 1.20000e-01 4.00000e+00]
[1.12834e+03 1.20000e-01 4.00000e+00]
[1.2478e+03 1.2000e-01 4.0000e+00]
[8.8639e+02 1.2000e-01 4.0000e+00]
[4.3923e+02 1.2000e-01 4.0000e+00]
[1.031e+03 1.200e-01 4.000e+00]
[2.60825e+03 1.20000e-01 4.00000e+00]
[1.80745e+03 1.20000e-01 4.00000e+00]
[1.18914e+03 1.20000e-01 4.00000e+00]
[1.098434e+03 1.100000e-01 4.000000e+00]
[7.8622e+02 1.1000e-01 4.0000e+00]
[7.4876e+02 1.1000e-01 4.0000e+00]
[1.2185e+02 1.1000e-01 4.0000e+00]
[1.63388e+03 1.10000e-01 4.00000e+00]
[2.61918e+03 1.00000e-01 4.00000e+00]
[1.82407e+03 1.00000e-01 4.00000e+00]
[6.3991e+02 1.0000e-01 4.0000e+00]
[1.98088e+03 1.00000e-01 4.00000e+00]
[1.59385e+03 9.00000e-02 4.00000e+00]
[9.2342e+02 9.0000e-02 4.0000e+00]
[5.5887e+02 9.0000e-02 4.0000e+00]
[1.4047e+02 9.0000e-02 4.0000e+00]
[2.3095e+02 9.0000e-02 4.0000e+00]
[1.96572e+03 9.00000e-02 4.00000e+00]
[1.50091e+03 9.00000e-02 4.00000e+00]
[1.14975e+03 9.00000e-02 4.00000e+00]
[1.7696e+03 8.0000e-02 4.0000e+00]
[1.44656e+03 8.00000e-02 4.00000e+00]
[5.3227e+02 8.0000e-02 4.0000e+00]
[3.7281e+02 8.0000e-02 4.0000e+00]
[8.0709e+02 8.0000e-02 4.0000e+00]
[1.32027e+03 8.00000e-02 4.00000e+00]
[6.9537e+02 7.0000e-02 4.0000e+00]
[3.9799e+02 7.0000e-02 4.0000e+00]
[4.0124e+02 7.0000e-02 4.0000e+00]
[1.99775e+03 7.00000e-02 4.00000e+00]
[6.7798e+02 7.0000e-02 4.0000e+00]
[1.24698e+03 7.00000e-02 4.00000e+00]
[1.13344e+03 7.00000e-02 4.00000e+00]
[1.43088e+03 7.00000e-02 4.00000e+00]
[1.16997e+03 7.00000e-02 4.00000e+00]
[1.20035e+03 6.00000e-02 4.00000e+00]
[1.36112e+03 6.00000e-02 4.00000e+00]
[9.0643e+02 6.0000e-02 4.0000e+00]
[6.9127e+02 6.0000e-02 4.0000e+00]
[2.06356e+03 6.00000e-02 4.00000e+00]
[9.8897e+02 6.0000e-02 4.0000e+00]
[2.06536e+03 6.00000e-02 4.00000e+00]
[1.23239e+03 6.00000e-02 4.00000e+00]
[1.03349e+03 6.00000e-02 4.00000e+00]
[1.52969e+03 6.00000e-02 4.00000e+00]
[1.10577e+03 6.00000e-02 4.00000e+00]
[6.2987e+02 6.0000e-02 4.0000e+00]
[2.25785e+03 5.00000e-02 4.00000e+00]
[9.0867e+02 5.0000e-02 4.0000e+00]
[2.3119e+02 5.0000e-02 4.0000e+00]
[5.8213e+02 5.0000e-02 4.0000e+00]
[1.04347e+03 5.00000e-02 4.00000e+00]
[8.4443e+02 4.0000e-02 4.0000e+00]
[6.5655e+02 4.0000e-02 4.0000e+00]
[3.9757e+02 4.0000e-02 4.0000e+00]
[2.0232e+02 4.0000e-02 4.0000e+00]
[3.6339e+02 4.0000e-02 4.0000e+00]
[9.6325e+02 4.0000e-02 4.0000e+00]
[1.60576e+03 4.00000e-02 4.00000e+00]
[1.67616e+03 4.00000e-02 4.00000e+00]
[1.7657e+03 4.0000e-02 4.0000e+00]
[3.9924e+02 4.0000e-02 4.0000e+00]
[1.82155e+03 4.00000e-02 4.00000e+00]
[1.20711e+03 3.00000e-02 4.00000e+00]
[1.373e+02 3.000e-02 4.000e+00]
[1.09475e+03 3.00000e-02 4.00000e+00]
[8.5882e+02 3.0000e-02 4.0000e+00]
[9.6788e+02 3.0000e-02 4.0000e+00]
[6.964e+02 3.000e-02 4.000e+00]
[1.17863e+03 3.00000e-02 4.00000e+00]
[1.78855e+03 3.00000e-02 4.00000e+00]
[1.68612e+03 2.00000e-02 4.00000e+00]
[9.7752e+02 2.0000e-02 4.0000e+00]
[2.48865e+03 2.00000e-02 4.00000e+00]
[1.7535e+03 2.0000e-02 4.0000e+00]
[1.72666e+03 2.00000e-02 4.00000e+00]
[1.31985e+03 2.00000e-02 4.00000e+00]
[9.0632e+02 2.0000e-02 4.0000e+00]
[9.8591e+02 2.0000e-02 4.0000e+00]
[2.6885e+03 2.0000e-02 4.0000e+00]
[1.6166e+03 2.0000e-02 4.0000e+00]
[1.47428e+03 2.00000e-02 4.00000e+00]
[2.1112e+03 1.0000e-02 4.0000e+00]
[2.12616e+03 1.00000e-02 4.00000e+00]
[1.70194e+03 1.00000e-02 4.00000e+00]
[8.262e+02 1.000e-02 4.000e+00]
[9.46e+02 1.00e-02 4.00e+00]
[1.78106e+03 1.00000e-02 4.00000e+00]
[1.58132e+03 1.00000e-02 4.00000e+00]
[5.7173e+02 1.0000e-02 4.0000e+00]
[1.39191e+03 1.00000e-02 4.00000e+00]
[1.57299e+03 1.00000e-02 4.00000e+00]
[1.41247e+03 1.00000e-02 4.00000e+00]
[2.18261e+03 1.00000e-02 4.00000e+00]

In [92]:
dur_4

           0     1  2
36    696.90  5.12  4
142   900.44  4.09  4
30    250.12  3.21  4
41   1362.75  3.18  4
375  1113.53  2.87  4
..       ...   ... ..
79    571.73  0.01  4
247  1391.91  0.01  4
415  1572.99  0.01  4
44   1412.47  0.01  4
407  2182.61  0.01  4

[430 rows x 3 columns]

In [2]:
#duration_1[1][1:][:]

In [1]:
for i in range(4, -1, -1):
    print(i)

4
3
2
1
0

In [99]:
import os
import pandas as pd

files = os.listdir('data\\AMI\\Count')
    
#DATA = pd.read_csv('data\\AMI\\Count\\' + files[0], delimiter=',')

DATA = pd.DataFrame({'start': [], 'duration': [], 'count': []})

In [100]:
for f in files[2:3]:
    file_csv = 'data\\AMI\\Count\\' + f # путь к файлам

    data = pd.read_csv(file_csv, delimiter=',') # колонки - start, duration, count или (start, end, duration, count)
    
    #DATA.join(data)
    DATA = pd.concat([DATA, data])

In [101]:
DATA

        start    duration  count
0        0.00   20.840000    0.0
1       20.84    0.490000    1.0
2       21.33   15.970000    0.0
3       37.30    0.570000    1.0
4       37.87    9.120000    0.0
...       ...         ...    ...
1280  3351.71    3.690000    0.0
1281  3355.40    6.630000    1.0
1282  3362.03    1.410000    0.0
1283  3363.44    2.960000    1.0
1284  3366.40  179.978687    0.0

[1285 rows x 3 columns]

In [102]:
count = DATA.values    

duration = [[], [], [], [], []]

for st, dur, cnt in count:
    duration[int(cnt)].append([st, dur, int(cnt)])

In [15]:
#duration

In [104]:
count_1 = []

for i in range(4, -1, -1):

    dur = pd.DataFrame(duration[i])
    if len(dur) > 0: dur = dur.sort_values(by=1, ascending=False) # сортировка по 
    dur = dur.values

    np.random.shuffle(dur)  # перемешивание массива  

    len_cnt = 0
    if i == 4:
        len_max = 0
    for st, d, pers in dur:
        if d > 0.2 and (len_cnt < len_max or i == 4):
            count_1.append([st, d, int(pers)])
            len_cnt += d
            if i == 4:
                len_max += d

count_2 = pd.DataFrame(count_1)
if len(count_2) > 0: count_2 = count_2.sort_values(by=0)
count_2 = count_2.values
if len(count_2) == 0: count_2 = [0, 0, 0]

In [103]:
for i in range(4, -1, -1):

    dur = pd.DataFrame(duration[i])
    print(len(dur))

5
29
330
613
308

In [67]:
if len(count_2) == 0: count_2 = [0, 0, 0]

In [119]:
count_3 = np.array([[0, 0, 0]])

In [120]:
print(count_3)

[[0 0 0]]

In [116]:
count_2

array([[3.47560e+02, 5.00000e-01, 0.00000e+00],
       [1.12945e+03, 4.80000e-01, 4.00000e+00],
       [1.24701e+03, 1.77000e+00, 3.00000e+00],
       [1.71485e+03, 1.36000e+00, 1.00000e+00],
       [1.77098e+03, 2.40000e-01, 4.00000e+00],
       [2.29741e+03, 7.90000e-01, 0.00000e+00],
       [2.77336e+03, 3.90000e-01, 2.00000e+00],
       [3.24273e+03, 3.40000e-01, 2.00000e+00]])

In [125]:
import numpy as np

INTER = pd.DataFrame(count_2, columns=['start', 'duration', 'count'])
#INTER.to_csv('outputs\\Ideal\\AMIcsv_new\\' + file_au + '.count.csv', index=False)

In [126]:
INTER

     start  duration  count
0   347.56      0.50    0.0
1  1129.45      0.48    4.0
2  1247.01      1.77    3.0
3  1714.85      1.36    1.0
4  1770.98      0.24    4.0
5  2297.41      0.79    0.0
6  2773.36      0.39    2.0
7  3242.73      0.34    2.0

In [5]:
import numpy as np
import pickle
import os.path
import xml.etree.ElementTree as ET 
import re
import pandas as pd


#path = 'outputs\\AMIwords\\'
path = 'outputs\\AMIsegments\\'

fnames_cur = os.listdir(path)
print('Количество файлов в папке:', len(fnames_cur))


path_f = []
files_audio = []
for d, dirs, files in os.walk('F:\\amicorpus_1'): # путь к файлам
    for f in files:
        path_1 = os.path.join(d,f) # формирование адреса
        #if f.split('.')[0] != 'ES2002d':
        path_f.append(path_1) # добавление адреса в список
        files_audio.append(f.split('.')[0])

files_audio = list(set(files_audio))

length = {}
a = 2
        
######## Подготовка csv для каждого аудио
for file_au in files_audio[:1]:

    print(file_au)

    files = []
    for name in fnames_cur:
        if file_au in name:
            files.append(name)

    data = []
    for file in files:

        tree = ET.parse(path + file)
        root = tree.getroot()

        person = file.split('.')[1]

        #for dt in root.findall('w'):
        for dt in root.findall('segment'):
            #if dt.get('punc') is None and dt.get('starttime') is not None:
            #    if data != [] and data[-1][1] == float(dt.get('starttime')):
            #        data[-1][1] = float(dt.get('endtime'))
            #    else:    
            data.append([float(dt.get('transcriber_start')), float(dt.get('transcriber_end')), person])

    #print(data)

Количество файлов в папке: 687
EN2006a

In [6]:
data_sort = sorted(data, key=lambda x: x[0])
DATA = pd.DataFrame(data_sort, columns=['start', 'end', 'person'])

In [15]:
DATA

        start  duration  count
0        0.00      3.34    0.0
1        3.34      0.54    1.0
2        3.88      1.69    0.0
3        5.57      0.03    1.0
4        5.60      0.34    2.0
...       ...       ...    ...
1411  2307.65      0.39    0.0
1412  2308.04      0.21    1.0
1413  2308.25     15.65    0.0
1414  2323.90      0.49    1.0
1415  2324.39     17.21    0.0

[164811 rows x 3 columns]

In [16]:

with np.load(os.path.join("models", 'scaler.npz')) as data:
    print(data['arr_0'].shape) #mean
    print(data['arr_1'].shape) #scale

(201,)
(201,)

In [31]:
import pickle 

name = 'EN2002b'

with open('outputs\model_0-4_1sec_stft\AMI_array1-01_amp4mean\pkl\\' + name + '.output_probs.pickle', 'rb') as f:
    pr_labels = pickle.load(f)

with open('outputs\model_0-4_1sec_stft\AMI_array1-01_amp4mean\pkl\\' + name + '.output.pickle', 'rb') as f:
    pr_labels_1 = pickle.load(f)

In [32]:
pr_labels = np.asarray(pr_labels)
pr_labels = np.argmax(pr_labels, axis=1)

In [37]:
print(pr_labels_1[0])

1

In [35]:
print(pr_labels)

[1 0 0 ... 1 4 3]

In [40]:
ggg = [[0, 3, 4], [1, 3, 4]]

for i, g, g1, g2 in enumerate(ggg):
    print(g)

ValueError: not enough values to unpack (expected 4, got 2)

In [14]:
import yaml

with open(r'yaml/train.yaml') as f:
    templates = yaml.load(f, Loader=yaml.FullLoader)

print(templates['batch_size'])

100

In [2]:
yaml.__version__

'5.3.1'